import {
  IServiceConfig,
  IServices,
} from '../views/home/interface/interfaceService';

export const services: IServices[] = [
  {
    name: 'SERVICE.CARTERA.NAME',
    route: 'cartera',
    dataValue: 'Portfolio',
    ariaLabel: 'Portfolio',
    iconSrc: '/icons/cartera.webp',
    iconAlt: 'Cartera',
    iconWidth: 34,
    iconHeight: 28,
  },
  {
    name: 'SERVICE.RESPONSABILIDAD.NAME',
    route: 'responsabilidad',
    dataValue: 'Liability',
    ariaLabel: 'Civil Liability',
    iconSrc: 'icons/igroup.webp',
    iconAlt: 'Responsabilidad Civil',
    iconWidth: 34,
    iconHeight: 28,
  },
  {
    name: 'SERVICE.INMOBILIARIA.NAME',
    route: 'inmobiliaria',
    dataValue: 'RealEstate',
    ariaLabel: 'Real Estate',
    iconSrc: '/icons/home.webp',
    iconAlt: 'inmobiliario',
    iconWidth: 34,
    iconHeight: 28,
  },
  {
    name: 'SERVICE.LABORAL.NAME',
    route: 'laboral',
    dataValue: 'SmallBusiness',
    ariaLabel: 'Labor and Commercial',
    iconSrc: '/icons/bolso.webp',
    iconAlt: 'laboral',
    iconWidth: 34,
    iconHeight: 28,
  },
  {
    name: 'SERVICE.PROPIEDAD.NAME',
    route: 'propiedad-horizontal',
    dataValue: 'PropertyManagement',
    ariaLabel: 'Property Management',
    iconSrc: '/icons/icon-edificio.svg',
    iconAlt: 'propiedad horizontal',
    iconWidth: 41,
    iconHeight: 50,
  },
  {
    name: 'SERVICE.COMERCIAL.NAME',
    route: 'derecho-comercial',
    dataValue: 'Commercial',
    ariaLabel: 'Commercial Law',
    iconSrc: '/icons/icon-peso-blanco.svg',
    iconAlt: 'derecho comercial',
    iconWidth: 41,
    iconHeight: 50,
  },
];

export const SERVICE_DATA: Record<string, IServiceConfig> = {
  cartera: {
    title: 'SERVICE.CARTERA.TITLE',
    imageSrc: 'img/servicios/service_cartera_legaltech.png',
    imageAlt: 'Cobro de Cartera',
    description: 'SERVICE.CARTERA.DESCRIPTION',
    bulletPoints: [
      'SERVICE.CARTERA.BULLETS.ONE',
      'SERVICE.CARTERA.BULLETS.TWO',
      'SERVICE.CARTERA.BULLETS.THREE',
      'SERVICE.CARTERA.BULLETS.FOUR',
    ],
  },
  inmobiliaria: {
    title: 'SERVICE.INMOBILIARIA.TITLE',
    imageSrc: 'img/servicios/service_inmobiliaria_legaltech.png',
    imageAlt: 'Derecho Inmobiliario',
    description: 'SERVICE.INMOBILIARIA.DESCRIPTION',
    bulletPoints: [
      'SERVICE.INMOBILIARIA.BULLETS.ONE',
      'SERVICE.INMOBILIARIA.BULLETS.TWO',
      'SERVICE.INMOBILIARIA.BULLETS.THREE',
      'SERVICE.INMOBILIARIA.BULLETS.FOUR',
      'SERVICE.INMOBILIARIA.BULLETS.FIVE',
    ],
  },
  responsabilidad: {
    title: 'SERVICE.RESPONSABILIDAD.TITLE',
    imageSrc: '/icons/responsabilidad_civil.svg',
    imageAlt: 'Responsabilidad Civil',
    description: 'SERVICE.RESPONSABILIDAD.DESCRIPTION',
    bulletPoints: [
      'SERVICE.RESPONSABILIDAD.BULLETS.ONE',
      'SERVICE.RESPONSABILIDAD.BULLETS.TWO',
      'SERVICE.RESPONSABILIDAD.BULLETS.THREE',
      'SERVICE.RESPONSABILIDAD.BULLETS.FOUR',
    ],
  },
  laboral: {
    title: 'SERVICE.LABORAL.TITLE',
    imageSrc: '/icons/derecho_laboral.svg',
    imageAlt: 'Derecho Laboral',
    description: 'SERVICE.LABORAL.DESCRIPTION',
    bulletPoints: [
      'SERVICE.LABORAL.BULLETS.ONE',
      'SERVICE.LABORAL.BULLETS.TWO',
      'SERVICE.LABORAL.BULLETS.THREE',
      'SERVICE.LABORAL.BULLETS.FOUR',
      'SERVICE.LABORAL.BULLETS.FIVE',
    ],
  },
  'propiedad-horizontal': {
    title: 'SERVICE.PROPIEDAD.TITLE',
    imageSrc: '/icons/propiedad_horizontal.svg',
    imageAlt: 'Propiedad Horizontal',
    description: 'SERVICE.PROPIEDAD.DESCRIPTION',
    bulletPoints: [
      'SERVICE.PROPIEDAD.BULLETS.ONE',
      'SERVICE.PROPIEDAD.BULLETS.TWO',
      'SERVICE.PROPIEDAD.BULLETS.THREE',
      'SERVICE.PROPIEDAD.BULLETS.FOUR',
      'SERVICE.PROPIEDAD.BULLETS.FIVE',
    ],
  },
  'derecho-comercial': {
    title: 'SERVICE.COMERCIAL.TITLE',
    imageSrc: '/icons/derecho_laboral.svg',
    imageAlt: 'Derecho Comercial',
    description: 'SERVICE.COMERCIAL.DESCRIPTION',
    bulletPoints: [
      'SERVICE.COMERCIAL.BULLETS.ONE',
      'SERVICE.COMERCIAL.BULLETS.TWO',
      'SERVICE.COMERCIAL.BULLETS.THREE',
      'SERVICE.COMERCIAL.BULLETS.FOUR',
      'SERVICE.COMERCIAL.BULLETS.FIVE',
    ],
  },
  defaul: {
    title: 'SERVICE.DEFAULT.TITLE',
    imageSrc: 'img/servicios/service_laboral_comercial_legaltech.png',
    imageAlt: 'Servicios Legales',
    description: 'SERVICE.DEFAULT.DESCRIPTION',
    bulletPoints: [],
  },
};
