# Usa una imagen base de Node
FROM node:18-alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos sólo los package*.json para instalar dependencias
COPY package*.json ./

# Instalamos las dependencias
RUN npm install

# Opción A:
# Asumimos que en tu package.json tienes un script "start" que hace "ng serve --host 0.0.0.0"
# CMD ["npm", "start"]

# Opción B:
# Si prefieres no depender de tu script "start", puedes usar:
CMD ["npx", "ng", "serve", "--host", "0.0.0.0"]
