version: '3.8'
services:
  frontend:
    # Construye usando el Dockerfile.dev
    build:
      context: .
      dockerfile: dockerfile.dev
    # Mapeamos el puerto 4200 del contenedor al 4200 local
    ports:
      - "4200:4200"
    # Volúmenes para mantener el código sincronizado
    volumes:
      # Mapeamos todo el código local en /app
      - .:/app
      # Evitamos que la carpeta node_modules del host se mezcle con la del contenedor
      - /app/node_modules
